### ISSUE TITLE
The CI deployment to Ansible Galaxy fails

### ISSUE THREAD

**Issue by FergusFettes** [Provizanta/ansible-role-nvidia-cuda#1]
Hi, I think you need to push the latest version to ansible-galaxy, as the install fails when you do it with `ansible-galaxy install` but it works fine if you just clone the repo into the right folder. If you update it I'll give it a five start rating on ansible-galaxy :).

**Comment by Teebor-Choka** [comment]
Fixed by #2.

Also, this is a bug concerning **all** *Provizanta* repositories, so thank you for finding that. I've added it to my task list.

:+1:

**Comment by FergusFettes** [comment]
This seems to be broken again, installing with git clone works but ansible galaxy not.

**Comment by Teebor-Choka** [comment]
Thanks for letting me know. Fixed in #3 (and verified). The role now has an Ansible Galaxy compliant name `nvidia_cuda`. enjoy. :beer:
